package com.clip.tlv.model

val Commands = mapOf(
        "9F01" to Command("9F01", "Acquirer Identifier"),
        "9F40" to Command("9F40", "Additional Terminal Capabilities"),
        "81" to Command("81", "Amount, Authorised (Binary)"),
        "9F02" to Command("9F02", "Amount, Authorised (Numeric)"),
        "9F04" to Command("9F04", "Amount, Other (Binary)"),
        "9F03" to Command("9F03", "Amount, Other (Numeric)"),
        "9F3A" to Command("9F3A", "Amount, Reference Currency"),
        "9F26" to Command("9F26", "Application Cryptogram"),
        "9F42" to Command("9F42", "Application Currency Code"),
        "9F44" to Command("9F44", "Application Currency Exponent"),
        "9F05" to Command("9F05", "Application Discretionary Data"),
        "5F25" to Command("5F25", "Application Effective Date"),
        "5F24" to Command("5F24", "Application Expiration Date"),
        "94" to Command("94", "Application File Locator (AFL)"),
        "4F" to Command("4F", "Application Identifier (AID) – card"),
        "9F06" to Command("9F06", "Application Identifier (AID) – terminal"),
        "82" to Command("82", "Application Interchange Profile"),
        "50" to Command("50", "Application Label"),
        "9F12" to Command("9F12", "Application Preferred Name", TYPE_DATA.STRING_DATA),
        "5A" to Command("5A", "Application Primary Account Number (PAN)"),
        "5F34" to Command("5F34", "Application Primary Account Number (PAN) Sequence Number"),
        "87" to Command("87", "Application Priority Indicator"),
        "9F3B" to Command("9F3B", "Application Reference Currency"),
        "9F43" to Command("9F43", "Application Reference Currency Exponent"),
        "—" to Command("—", "Application Selection Indicator"),
        "61" to Command("61", "Application Template"),
        "9F36" to Command("9F36", "Application Transaction Counter (ATC)"),
        "9F07" to Command("9F07", "Application Usage Control"),
        "9F08" to Command("9F08", "Application Version Number"),
        "9F09" to Command("9F09", "Application Version Number"),
        "89" to Command("89", "Authorisation Code"),
        "8A" to Command("8A", "Authorisation Response Code"),
        "—" to Command("—", "Authorisation Response Cryptogram (ARPC)"),
        "5F54" to Command("5F54", "Bank Identifier Code (BIC)"),
        "8C" to Command("8C", "Card Risk Management Data Object List 1 (CDOL1)"),
        "8D" to Command("8D", "Card Risk Management Data Object List 2 (CDOL2)"),
        "—" to Command("—", "Card Status Update (CSU)"),
        "5F20" to Command("5F20", "Cardholder Name", TYPE_DATA.STRING_DATA),
        "9F0B" to Command("9F0B", "Cardholder Name Extended", TYPE_DATA.STRING_DATA),
        "8E" to Command("8E", "Cardholder Verification Method (CVM) List"),
        "9F34" to Command("9F34", "Cardholder Verification Method (CVM) Results"),
        "—" to Command("—", "Certification Authority Public Key Check Sum"),
        "—" to Command("—", "Certification Authority Public Key Exponent"),
        "8F" to Command("8F", "Certification Authority Public Key Index"),
        "9F22" to Command("9F22", "Certification Authority Public Key Index"),
        "—" to Command("—", "Certification Authority Public Key Modulus"),
        "83" to Command("83", "Command Template"),
        "9F27" to Command("9F27", "Cryptogram Information Data"),
        "9F45" to Command("9F45", "Data Authentication Code"),
        "84" to Command("84", "Dedicated File (DF) Name"),//,TYPE_DATA.STRING_DATA),
        "—" to Command("—", "Default Dynamic Data Authentication Data Object List (DDOL)"),
        "—" to Command("—", "Default Transaction Certificate Data Object List (TDOL)"),
        "9D" to Command("9D", "Directory Definition File (DDF) Name",TYPE_DATA.STRING_DATA),
        "73" to Command("73", "Directory Discretionary Template"),
        "9F49" to Command("9F49", "Dynamic Data Authentication Data Object List (DDOL)"),
        "70" to Command("70", "EMV Proprietary Template"),
        "—" to Command("—", "Enciphered Personal Identification Number (PIN) Data"),
        "BF0C" to Command("BF0C", "File Control Information (FCI) Issuer Discretionary Data"),
        "A5" to Command("A5", "File Control Information (FCI) Proprietary Template"),
        "6F" to Command("6F", "File Control Information (FCI) Template"),
        "9F4C" to Command("9F4C", "ICC Dynamic Number"),
        "9F2D" to Command("9F2D", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate"),
        "9F2E" to Command("9F2E", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent"),
        "9F2F" to Command("9F2F", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder"),
        "9F46" to Command("9F46", "Integrated Circuit Card (ICC) Public Key Certificate"),
        "9F47" to Command("9F47", "Integrated Circuit Card (ICC) Public Key Exponent"),
        "9F48" to Command("9F48", "Integrated Circuit Card (ICC) Public Key Remainder"),
        "9F1E" to Command("9F1E", "Interface Device (IFD) Serial Number", TYPE_DATA.STRING_DATA),
        "5F53" to Command("5F53", "International Bank Account Number (IBAN)"),
        "9F0D" to Command("9F0D", "Issuer Action Code – Default"),
        "9F0E" to Command("9F0E", "Issuer Action Code – Denial"),
        "9F0F" to Command("9F0F", "Issuer Action Code – Online"),
        "9F10" to Command("9F10", "Issuer Application Data"),
        "91" to Command("91", "Issuer Authentication Data"),
        "9F11" to Command("9F11", "Issuer Code Table Index"),
        "5F28" to Command("5F28", "Issuer Country Code"),
        "5F55" to Command("5F55", "Issuer Country Code (alpha2 format)"),
        "5F56" to Command("5F56", "Issuer Country Code (alpha3 format)"),
        "42" to Command("42", "Issuer Identification Number (IIN)"),
        "90" to Command("90", "Issuer Public Key Certificate"),
        "9F32" to Command("9F32", "Issuer Public Key Exponent"),
        "92" to Command("92", "Issuer Public Key Remainder"),
        "86" to Command("86", "Issuer Script Command"),
        "9F18" to Command("9F18", "Issuer Script Identifier"),
        "—" to Command("—", "Issuer Script Results"),
        "71" to Command("71", "Issuer Script Template 1"),
        "72" to Command("72", "Issuer Script Template 2"),
        "5F50" to Command("5F50", "Issuer URL"),
        "5F2D" to Command("5F2D", "Language Preference"),
        "9F13" to Command("9F13", "Last Online Application Transaction Counter (ATC) Register"),
        "9F4D" to Command("9F4D", "Log Entry"),
        "9F4F" to Command("9F4F", "Log Format"),
        "9F14" to Command("9F14", "Lower Consecutive Offline Limit"),
        "—" to Command("—", "Maximum Target Percentage to be used for Biased Random Selection"),
        "9F15" to Command("9F15", "Merchant Category Code"),
        "9F16" to Command("9F16", "Merchant Identifier",TYPE_DATA.STRING_DATA),
        "9F4E" to Command("9F4E", "Merchant Name and Location", TYPE_DATA.STRING_DATA),
        "—" to Command("—", "Message Type"),
        "—" to Command("—", "Personal Identification Number (PIN) Pad Secret Key"),
        "9F17" to Command("9F17", "Personal Identification Number (PIN) Try Counter"),
        "9F39" to Command("9F39", "Point-of-Service (POS) Entry Mode"),
        "9F38" to Command("9F38", "Processing Options Data Object List (PDOL)"),
        "—" to Command("—", "Proprietary Authentication Data"),
        "80" to Command("80", "Response Message Template Format 1"),
        "77" to Command("77", "Response Message Template Format 2"),
        "5F30" to Command("5F30", "Service Code"),
        "88" to Command("88", "Short File Identifier (SFI)"),
        "9F4B" to Command("9F4B", "Signed Dynamic Application Data"),
        "93" to Command("93", "Signed Static Application Data"),
        "9F4A" to Command("9F4A", "Static Data Authentication Tag List"),
        "—" to Command("—", "Target Percentage to be Used for Random Selection"),
        "—" to Command("—", "Terminal Action Code – Default"),
        "—" to Command("—", "Terminal Action Code – Denial"),
        "—" to Command("—", "Terminal Action Code – Online"),
        "9F33" to Command("9F33", "Terminal Capabilities"),
        "9F1A" to Command("9F1A", "Terminal Country Code"),
        "9F1B" to Command("9F1B", "Terminal Floor Limit"),
        "9F1C" to Command("9F1C", "Terminal Identification"),
        "9F1D" to Command("9F1D", "Terminal Risk Management Data"),
        "9F35" to Command("9F35", "Terminal Type"),
        "95" to Command("95", "Terminal Verification Results"),
        "—" to Command("—", "Threshold Value for Biased Random Selection"),
        "9F1F" to Command("9F1F", "Track 1 Discretionary Data"),
        "9F20" to Command("9F20", "Track 2 Discretionary Data"),
        "57" to Command("57", "Track 2 Equivalent Data"),
        "—" to Command("—", "Transaction Amount"),
        "98" to Command("98", "Transaction Certificate (TC) Hash Value"),
        "97" to Command("97", "Transaction Certificate Data Object List (TDOL)"),
        "5F2A" to Command("5F2A", "Transaction Currency Code"),
        "5F36" to Command("5F36", "Transaction Currency Exponent"),
        "9A" to Command("9A", "Transaction Date"),
        "99" to Command("99", "Transaction Personal Identification Number (PIN) Data"),
        "9F3C" to Command("9F3C", "Transaction Reference Currency Code"),
        "—" to Command("—", "Transaction Reference Currency Conversion"),
        "9F3D" to Command("9F3D", "Transaction Reference Currency Exponent"),
        "9F41" to Command("9F41", "Transaction Sequence Counter"),
        "9B" to Command("9B", "Transaction Status Information"),
        "9F21" to Command("9F21", "Transaction Time"),
        "9C" to Command("9C", "Transaction Type"),
        "9F37" to Command("9F37", "Unpredictable Number"),
        "9F23" to Command("9F23", "Upper Consecutive Offline Limit")
        )

enum class TYPE_DATA{
    STRING_DATA,INTEGER_DATA, PRIMITIVE_DATA
}
data class Command(val command:String,val name:String,var type:TYPE_DATA = TYPE_DATA.PRIMITIVE_DATA)